const dictionary = [
  'pumpkin spice',
  'sweater',
  'cozy',
  'crisp',
  'brisk',
  'nippy',
  'fireplace',
  'Uggs',
  'hoodie',
  'Lululemon',
  'candles',
  'shearling',
  'throw rug',
  'jack-o-lantern',
  'hayride',
  'falling leaves',
  'chill in the air',
  'booties',
  'knee socks',
  'leggings',
  'salted caramel',
  'hygge',
  'cabin',
  'snuggling',
  'jacket',
  'maple syrup',
  'cinnamon',
  'cloves',
  'allspice',
  'nutmeg',
  'mulled cider',
  'hot chocolate',
  'latte',
  'long johns',
  'knitted',
  'wool',
  'scarf',
  'mittens',
  'apple cider',
  'cider donut',
  'apple picking',
  'apple pie',
  'pumpkin pie',
  'hiking',
  'Octoberfest',
  'campfire',
  'foliage',
  'festival',
  'sunset',
  'squash',
  'decorative gourd',
  'tablescape',
  'Halloween',
  'autumn',
  'fall',
  'leafpeepers',
  'bonfire',
  'mug',
];

export default dictionary;
